#!/bin/bash

d=-  # depending on driver

declare -A screens=(
    [hdmi]="HDMI${d}2"
    [dvi]="HDMI${d}1"
    [dp]="DP${d}2-2"
)

declare -A configs=(
    [left]="--left-of eDP${d}1 --auto"
    [left fullhd]="--left-of eDP${d}1 --mode 1920x1080"
    [right]="--right-of eDP${d}1 --auto"
    [same]="--same-as eDP${d}1 --auto"
)

connected_screens=()
for name in "${!screens[@]}"; do
    if xrandr | grep -q "${screens[$name]} connected"; then
        connected_screens+="$name"
    fi
done

screen=$(printf '%s\n' "${connected_screens[@]}" "internal" | rofi -dmenu -p "screen")
[[ $? != 0 ]] && exit 1
if [[ $screen == internal ]]; then
    xrandr --output "${screens[hdmi]}" --off --output "${screens[dvi]}" --off --output "${screens[dp]}" --off
else

    config=$(printf '%s\n' "${!configs[@]}" | rofi -dmenu -p "config")
    [[ $? != 0 ]] && exit 1
    xrandr --output "${screens[$screen]}" ${configs[$config]}
fi

herbstclient detect_monitors
herbstclient reload

# FIXME are those IDs fixed?
xinput map-to-output 9 eDP${d}1
xinput map-to-output 20 eDP${d}1
