#!/bin/bash

declare -A screens=(
    [hdmi]="HDMI-A-0"
    [dp1]="DisplayPort-0"
    [dp2]="DisplayPort-1"
    [hdmi-dock]="DisplayPort-2"
    [hdmi-dock-2]="DisplayPort-3"
)

declare -A configs=(
    [left]="--left-of eDP --auto"
    [left fullhd]="--left-of eDP --mode 1920x1080"
    [right]="--right-of eDP --auto"
    [same]="--same-as eDP --auto"
)

connected_screens=()
for name in "${!screens[@]}"; do
    if xrandr | grep -q "^${screens[$name]} connected"; then
        connected_screens+=("$name")
    fi
done

screen=$(printf '%s\n' "${connected_screens[@]}" "internal" | rofi -dmenu -p "screen" -m -5)
[[ $? != 0 ]] && exit 1
if [[ $screen == internal ]]; then
    xrandr --output "${screens[hdmi]}" --off --output "${screens[hdmi]}" --off --output "${screens[dp1]}" --off --output "${screens[dp2]}" --off --output "${screens[hdmi-dock]}" --off --output "${screens[hdmi-dock-2]}" --off
else

    config=$(printf '%s\n' "${!configs[@]}" | rofi -dmenu -p "config" -m -5)
    [[ $? != 0 ]] && exit 1
    xrandr --output "${screens[$screen]}" ${configs[$config]}
fi

herbstclient detect_monitors
herbstclient emit_hook quit_panel
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    barpyrus $monitor &
done
[[ -f ~/.fehbg ]] && ~/.fehbg &
